language: node_js
node_js:
- 10
install:
- yarn install
script:
- yarn test
deploy:
  provider: npm
  cleanup: true
  edge: true
  email: aleksandryackovlev@yandex.ru
  on:
    tags: true
    repo: aleksandryackovlev/json-schema-faker-types
  api_key:
    secure: tZ0CgpnnmGfpx4oBnEnyhteXgMn5KopQxW+66lhl+gZ+CiXhPEP1VJwF/8t/UvlMALhUJN1vH9ITxSNuDJ8QAdMbQZ+U3L2r2BSbNhByqQi+poAHOSil7OiItzKmWpwVhs5TXmBtjg/29OCuObkXZ2MVYNR0dmx+N8ReHdIqitkFyEXfXZrgO+l0YxdRSxe/sUcbCu8Vqw5o8TiSAha5InZ5uwvG36IKxljpBmZSybiE8uZeBqD7J8plhgUq7+2SxH8JyT3aBd1dcRQjuPVhxYUlKPYzLFCykTB0Ll8zikSFHgINAzpZpvTFsgqW6000sHt9G+y6bsRCMggLiradhxsqk9OmxkDb3/6a0+8N5hTXtx75UePhuwnukoiYOzk5qFZ/Bl5BjNArsTBoEaN8AOlANGmPIu89SUdtIeYpDJda4IzH/hauqfCgjUDwEZTFYAnclFgbI5HYVM9uYQKFkQUKEMVrnLHsFsstgRCR54NzVIHwgttbLyoVgqdH++6QfpOLA2lEnj1dMieFpD+yhBLWW350hj9YjDjeTqqupyGlb0D84xNTN0mSnZFG62X9OhZHnE8GcBaEl4EXDYCsdu4bg4S6/o2KuD+OGnn74dxB6LKOpwULTogEsifEMV3SvgstEszJa5yn20H9taZX0e7eAEzIY4zGwQuaCBKKKDw=
